### ISSUE TITLE
Load existing repository not working

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#106]
I've got an existing repository, cloned from BitBucket. I tried to open it via the + button and choosing "Load existing repository". The first time I got a generic error message. The second time I got no error message, but it didn't load.

**Comment by dmusican** [comment]
Ah, here's some detail:

org.eclipse.jgit.errors.MissingObjectException: Missing unknown 2a2ef7860eaca997b9263be48b1fc81595b2f6db
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:148)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:229)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:839)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:752)
	at main.java.elegit.RepoHelper.parseRawCommits(RepoHelper.java:606)
	at main.java.elegit.RepoHelper.getNewCommits(RepoHelper.java:459)
	at main.java.elegit.RepoHelper.getNewLocalCommits(RepoHelper.java:419)
	at main.java.elegit.LocalCommitTreeModel.getNewCommits(LocalCommitTreeModel.java:26)
	at main.java.elegit.CommitTreeModel.getNewCommits(CommitTreeModel.java:79)
	at main.java.elegit.CommitTreeModel.addNewCommitsToTree(CommitTreeModel.java:173)
	at main.java.elegit.CommitTreeModel.update(CommitTreeModel.java:138)
	at main.java.elegit.SessionController$7.lambda$call$29(SessionController.java:633)
	at main.java.elegit.SessionController$7$$Lambda$144/1404595625.run(Unknown Source)
	at com.sun.javafx.application.PlatformImpl.lambda$null$170(PlatformImpl.java:295)
	at com.sun.javafx.application.PlatformImpl$$Lambda$51/1034273363.run(Unknown Source)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$171(PlatformImpl.java:294)
	at com.sun.javafx.application.PlatformImpl$$Lambda$50/895792688.run(Unknown Source)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)

**Comment by dmusican** [comment]
I see. The missing commit above (2a2ef) was not in the repo that I was trying to load, but was in the active repo loaded at the time. These are getting convoluted somehow.

**Comment by dmusican** [comment]
Eric says this is fixed now, but we should have a unit test
