### ISSUE TITLE
Figure out what's going wrong with this exception

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#111]
This happened to me when trying to clone a repo, hitting cancel at the login screen, then trying to clone another repo.

Eric: see if it's a cancel bug. If not or can't tell, toss to Kiley

com.intellij.rt.execution.application.AppMain main.java.elegit.Main
org.eclipse.jgit.errors.MissingObjectException: Missing unknown 83b0bc04ad84675eacd477b4d08ceb585bbbc5be
	at org.eclipse.jgit.internal.storage.file.WindowCursor.open(WindowCursor.java:148)
	at org.eclipse.jgit.lib.ObjectReader.open(ObjectReader.java:229)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:840)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:753)
	at main.java.elegit.RepoHelper.parseRawCommits(RepoHelper.java:750)
	at main.java.elegit.RepoHelper.getNewCommits(RepoHelper.java:603)
	at main.java.elegit.RepoHelper.getNewRemoteCommits(RepoHelper.java:576)
	at main.java.elegit.RemoteCommitTreeModel.getNewCommits(RemoteCommitTreeModel.java:26)
	at main.java.elegit.CommitTreeModel.getNewCommits(CommitTreeModel.java:78)
	at main.java.elegit.CommitTreeModel.addNewCommitsToTree(CommitTreeModel.java:172)
	at main.java.elegit.CommitTreeModel.update(CommitTreeModel.java:137)
	at main.java.elegit.SessionController$7.call(SessionController.java:670)
	at main.java.elegit.SessionController$7.call(SessionController.java:648)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

**Comment by dmusican** [comment]
Eric says gone.
