### ISSUE TITLE
Removing all repos gives NullPointerException

### ISSUE THREAD

**Issue by shangdrk** [dmusican/Elegit#151]
Currently if you remove all repos from Elegit, a NullPointerException gets triggered:

> java.lang.NullPointerException
	at main.java.elegit.SessionController$12.call(SessionController.java:900)
	at main.java.elegit.SessionController$12.call(SessionController.java:894)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shangdrk** [comment]
I did a quick fix by checking if currentRepoHelper is null.
