### ISSUE TITLE
Cloning a repo causes NullPointerException

### ISSUE THREAD

**Issue by shangdrk** [dmusican/Elegit#152]
The stack trace:

> java.lang.NullPointerException
	at main.java.elegit.CommitTreeModel.addInvisibleCommit(CommitTreeModel.java:169)
	at main.java.elegit.CommitTreeController.init(CommitTreeController.java:167)
	at main.java.elegit.CommitTreeModel.initView(CommitTreeModel.java:330)
	at main.java.elegit.CommitTreeModel.init(CommitTreeModel.java:134)
	at main.java.elegit.SessionController.initPanelViews(SessionController.java:984)
	at main.java.elegit.SessionController.access$300(SessionController.java:59)
	at main.java.elegit.SessionController$1.call(SessionController.java:309)
	at main.java.elegit.SessionController$1.call(SessionController.java:301)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at main.java.elegit.RepoHelper.getNewCommits(RepoHelper.java:662)
	at main.java.elegit.RepoHelper.getNewRemoteCommits(RepoHelper.java:646)
	at main.java.elegit.RemoteCommitTreeModel.getNewCommits(RemoteCommitTreeModel.java:26)
	at main.java.elegit.CommitTreeModel.getNewCommits(CommitTreeModel.java:85)
	at main.java.elegit.CommitTreeModel.addNewCommitsToTree(CommitTreeModel.java:192)
	at main.java.elegit.CommitTreeModel.update(CommitTreeModel.java:144)
	at main.java.elegit.SessionController$12.call(SessionController.java:898)
	at main.java.elegit.SessionController$12.call(SessionController.java:893)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

**Comment by shangdrk** [comment]
After further experimenting, this exception only occurs when you use your account (say, GitHub) the first time. If you do a clone a second time, the program won't remember your account credentials, but it also won't crash after cloning.
