### ISSUE TITLE
NullPointerException on pushing

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#240]
This has happened to be a couple of times when trying to push:

java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:857)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at elegit.RepoHelper.parseRawCommits(RepoHelper.java:1053)
	at elegit.RepoHelper.parseRawCommits(RepoHelper.java:1080)
	at elegit.RepoHelper.parseAllRawRemoteCommits(RepoHelper.java:1025)
	at elegit.RepoHelper.parseAllRemoteCommits(RepoHelper.java:815)
	at elegit.RepoHelper.fetch(RepoHelper.java:510)
	at elegit.SessionController$8.call(SessionController.java:931)
	at elegit.SessionController$8.call(SessionController.java:926)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:857)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at elegit.RepoHelper.parseRawCommits(RepoHelper.java:1053)
	at elegit.RepoHelper.parseRawCommits(RepoHelper.java:1080)
	at elegit.RepoHelper.parseAllRawRemoteCommits(RepoHelper.java:1025)
	at elegit.RepoHelper.parseAllRemoteCommits(RepoHelper.java:815)
	at elegit.RepoHelper.updateModel(RepoHelper.java:235)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:99)
	at elegit.SessionController.lambda$gitStatus$7(SessionController.java:981)
	at com.sun.javafx.application.PlatformImpl.lambda$null$174(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$175(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
Exception in thread "Remote monitor for repository "Elegit"" java.lang.NullPointerException
	at elegit.RepositoryMonitor.lambda$watchRepoForRemoteChanges$93(RepositoryMonitor.java:92)
	at java.lang.Thread.run(Thread.java:745)

**Comment by connellyj** [comment]
I got the same thing when fetching (the line moved because the file was changed):

java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:857)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at elegit.RepoHelper.parseRawCommits(RepoHelper.java:1098)
	at elegit.RepoHelper.parseRawCommits(RepoHelper.java:1125)
	at elegit.RepoHelper.parseAllRawRemoteCommits(RepoHelper.java:1070)
	at elegit.RepoHelper.parseAllRemoteCommits(RepoHelper.java:860)
	at elegit.RepoHelper.updateModel(RepoHelper.java:235)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:102)
	at elegit.SessionController.lambda$gitStatus$7(SessionController.java:1103)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
java.lang.NullPointerException
	at org.eclipse.jgit.lib.ObjectIdOwnerMap.get(ObjectIdOwnerMap.java:131)
	at org.eclipse.jgit.revwalk.RevWalk.parseAny(RevWalk.java:857)
	at org.eclipse.jgit.revwalk.RevWalk.parseCommit(RevWalk.java:772)
	at elegit.RepoHelper.parseRawCommits(RepoHelper.java:1098)
	at elegit.RepoHelper.parseRawCommits(RepoHelper.java:1125)
	at elegit.RepoHelper.parseAllRawRemoteCommits(RepoHelper.java:1070)
	at elegit.RepoHelper.parseAllRemoteCommits(RepoHelper.java:860)
	at elegit.RepoHelper.fetch(RepoHelper.java:510)
	at elegit.SessionController$10.call(SessionController.java:1051)
	at elegit.SessionController$10.call(SessionController.java:1046)
	at javafx.concurrent.Task$TaskCallable.call(Task.java:1423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.lang.Thread.run(Thread.java:745)

**Comment by connellyj** [comment]
I think it has something to do with invisible commits not being where they should be...

**Comment by erictwalker18** [comment]
Indeed, invisible commits aren't being deleted, see #265
