### ISSUE TITLE
NullPointerException on fetching

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#355]
Got a null pointer exception after merging changes into master, pushing (which was fine), and then doing a fetch. Stack trace is below. Not sure how to duplicate apart from trying the above again and seeing if it happens. The problem happened in the "return" line below:

```java
    public int getAheadCount() throws IOException {
        if (this.branchModel.getCurrentBranch().getStatus() != null)
            return this.branchModel.getCurrentBranch().getStatus().getAheadCount();
        else return -1;
    }
```
At the very least, we should put in another appropriate null check and display useful information for diagnosing this if it happens?

```
Exception in thread "Remote monitor for repository "Elegit"" java.lang.NullPointerException
	at elegit.RepoHelper.getAheadCount(RepoHelper.java:450)
	at elegit.SessionController.updateStatusText(SessionController.java:230)
	at elegit.SessionController.lambda$initRepositoryMonitor$0(SessionController.java:278)
	at com.sun.javafx.binding.ExpressionHelper$SingleChange.fireValueChangedEvent(ExpressionHelper.java:182)
	at com.sun.javafx.binding.ExpressionHelper.fireValueChangedEvent(ExpressionHelper.java:81)
	at javafx.beans.property.BooleanPropertyBase.fireValueChangedEvent(BooleanPropertyBase.java:103)
	at javafx.beans.property.BooleanPropertyBase.markInvalid(BooleanPropertyBase.java:110)
	at javafx.beans.property.BooleanPropertyBase.set(BooleanPropertyBase.java:144)
	at elegit.RepositoryMonitor.setFoundNewChanges(RepositoryMonitor.java:143)
	at elegit.RepositoryMonitor.lambda$watchRepoForRemoteChanges$126(RepositoryMonitor.java:114)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by connellyj** [comment]
I think this got fixed when we fixed the missing-remote-tracking-branch issue. Will re-open if it happens again.

**Comment by connellyj** [comment]
This happened to me again, although I think for a different reason this time. Here's the stack trace:

`java.lang.NullPointerException
	at elegit.treefx.TreeGraphModel.setCellLabels(TreeGraphModel.java:267)
	at elegit.treefx.TreeGraphModel.setCellLabels(TreeGraphModel.java:257)
	at elegit.CommitTreeModel.updateAllRefLabels(CommitTreeModel.java:591)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:116)
	at elegit.SessionController.lambda$gitStatus$11(SessionController.java:1721)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)`
