### ISSUE TITLE
Can't create a branch from within Elegit

### ISSUE THREAD

**Issue by dmusican** [dmusican/Elegit#463]
Try to create a branch in master; this happens. We critically need a unit test for this first.

java.lang.NullPointerException
	at elegit.CommitTreeModel.addCommitRefMaps(CommitTreeModel.java:586)
	at elegit.CommitTreeModel.updateAllRefLabels(CommitTreeModel.java:563)
	at elegit.CommitTreeModel.resetBranchHeads(CommitTreeModel.java:617)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:113)
	at elegit.SessionController.lambda$gitStatus$17(SessionController.java:2198)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
Exception in thread "JavaFX Application Thread" java.lang.NullPointerException
	at org.controlsfx.control.PopOver.showFadeInAnimation(PopOver.java:458)
	at org.controlsfx.control.PopOver.show(PopOver.java:449)
	at org.controlsfx.control.PopOver.show(PopOver.java:370)
	at org.controlsfx.control.PopOver.show(PopOver.java:312)
	at org.controlsfx.control.PopOver.show(PopOver.java:280)
	at elegit.CreateDeleteBranchWindowController.lambda$updateUser$6(CreateDeleteBranchWindowController.java:408)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at elegit.CommitTreeModel.getChanges(CommitTreeModel.java:176)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:106)
	at elegit.SessionController.lambda$gitStatus$17(SessionController.java:2198)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at elegit.CommitTreeModel.getChanges(CommitTreeModel.java:176)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:106)
	at elegit.SessionController.lambda$gitStatus$17(SessionController.java:2198)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at elegit.CommitTreeModel.getChanges(CommitTreeModel.java:176)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:106)
	at elegit.SessionController.lambda$gitStatus$17(SessionController.java:2198)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)
java.lang.NullPointerException
	at elegit.CommitTreeModel.getChanges(CommitTreeModel.java:176)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:106)
	at elegit.SessionController.lambda$gitStatus$17(SessionController.java:2198)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.gtk.GtkApplication._runLoop(Native Method)
	at com.sun.glass.ui.gtk.GtkApplication.lambda$null$49(GtkApplication.java:139)
	at java.lang.Thread.run(Thread.java:745)

**Comment by erictwalker18** [comment]
Fixed the null pointer via #476, still need a unit test though
