### ISSUE TITLE
Create and checkout branch fails

### ISSUE THREAD

**Issue by erictwalker18** [dmusican/Elegit#478]
As seen when demoing Elegit, if you try to create and checkout a branch, it causes a NullPointerException:

java.lang.NullPointerException
	at elegit.CommitTreeModel.getChanges(CommitTreeModel.java:176)
	at elegit.CommitTreeModel.update(CommitTreeModel.java:106)
	at elegit.SessionController.lambda$gitStatus$17(SessionController.java:2218)
	at com.sun.javafx.application.PlatformImpl.lambda$null$173(PlatformImpl.java:295)
	at java.security.AccessController.doPrivileged(Native Method)
	at com.sun.javafx.application.PlatformImpl.lambda$runLater$174(PlatformImpl.java:294)
	at com.sun.glass.ui.InvokeLaterDispatcher$Future.run(InvokeLaterDispatcher.java:95)
	at com.sun.glass.ui.win.WinApplication._runLoop(Native Method)
	at com.sun.glass.ui.win.WinApplication.lambda$null$148(WinApplication.java:191)
	at java.lang.Thread.run(Thread.java:745)

**Comment by erictwalker18** [comment]
This happens when trying to create a new branch
